# Generated by Django 4.1.4 on 2023-01-02 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.district')),
            ],
        ),
        migrations.CreateModel(
            name='LocationFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('extra_description', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_facilities', to='parser.facility')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_facilities', to='parser.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='facilities',
            field=models.ManyToManyField(related_name='locations', through='parser.LocationFacilities', to='parser.facility'),
        ),
        migrations.CreateModel(
            name='FacilityTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('P', 'Premier'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('features', models.TextField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='parser.facility')),
            ],
        ),
        migrations.AddConstraint(
            model_name='locationfacilities',
            constraint=models.UniqueConstraint(fields=('location', 'facility'), name='no_duplicate_facility_at_location'),
        ),
    ]
