# Generated by Django 4.1.4 on 2023-01-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='slug',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
