# Generated by Django 4.1.4 on 2023-02-12 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_facility_alt_text_facility_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='location',
            old_name='address1',
            new_name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='park_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lower_age', models.IntegerField()),
                ('upper_age', models.IntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_drop_in', models.BooleanField()),
                ('program_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='parser.programcategory')),
            ],
        ),
    ]
