# Generated by Django 4.1.4 on 2023-03-12 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0008_rename_tiered_facilities_location_tier_facilities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='program',
            name='lower_age',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='program',
            name='upper_age',
        ),
        migrations.CreateModel(
            name='ProgramInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_age', models.IntegerField()),
                ('upper_age', models.IntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='parser.program')),
            ],
        ),
    ]
